(TeX-add-style-hook "end"
 (lambda ()
    (LaTeX-add-labels
     "sec:endomorphism-ring-of-an-elliptic-curve"
     "sec:isogenies"
     "eq:degree-of-composition"
     "prop:deg-phi-equals-sizeof-kernel"
     "sec:some-properties-ende"
     "ex:mult-by-m"
     "lem:mult-by-m-is-non-constant"
     "prop:End(E)-is-torsion-free"
     "cor:End(E)-is-char-zero-with-no-zero-divisors"
     "ex:cm-example"
     "ex:finite-field-cm"
     "prop:iso-curves-iso-end-rings"
     "sec:an-interlude-dual"
     "eq:dual-isogeny"
     "lem:properties-of-dual-isogenies"
     "prop:properties-of-m-dual"
     "cor:structure-of-E[m]"
     "sec:tate-module"
     "eq:structure-of-Tate-module"
     "eq:End(E)-to-T_ell(E)"
     "lem:End(E)-tensor-Z_ell-injects"
     "prop:rank-of-End(E)"
     "sec:action-of-Galois-on-m-torsion"
     "lem:E[m]-is-stable-under-Galois"
     "eq:Galois-representation"
     "sec:struct-ende-char-zero"
     "thm:structure-thm-for-End(E)")))

